spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      name: api-gateway

ureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true