name: Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy-dev:
    name: Deploy on Develop
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_INTEG_HOST }}
          username: ${{ secrets.HOSTS_USERNAME }}
          key: ${{ secrets.DEV_INTEG_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd AllConnected/${{ github.event.repository.name }}
            echo "Fetching latest code..."
            git fetch
            git checkout main
            git pull
            echo "Building Docker image..."
            docker build -t ${{ github.event.repository.name }} .
            echo "EUREKA_URL=http://discovery-service:8761/eureka" >> .env
            docker rm -f ${{ github.event.repository.name }}
            docker run --name ${{ github.event.repository.name }} --network all_connected -d -p 8080:8080 --env-file .env ${{ github.event.repository.name }}
            echo "Docker container running..."
            rm .env

  deploy-qa:
    name: Deploy on QA
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_INTEG_HOST }}
          username: ${{ secrets.HOSTS_USERNAME }}
          key: ${{ secrets.QA_INTEG_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd AllConnected/${{ github.event.repository.name }}
            echo "Fetching latest code..."
            git fetch
            git checkout main
            git pull
            echo "Building Docker image..."
            docker build -t ${{ github.event.repository.name }} .
            echo "EUREKA_URL=http://discovery-service:8761/eureka" >> .env
            docker rm -f ${{ github.event.repository.name }}
            docker run --name ${{ github.event.repository.name }} --network all_connected -d -p 8080:8080 --env-file .env ${{ github.event.repository.name }}
            echo "Docker container running..."
            rm .env

  deploy-prod:
    name: Deploy on Prod
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_INTEG_HOST }}
          username: ${{ secrets.HOSTS_USERNAME }}
          key: ${{ secrets.PROD_INTEG_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd AllConnected/${{ github.event.repository.name }}
            echo "Fetching latest code..."
            git fetch
            git checkout main
            git pull
            echo "Building Docker image..."
            docker build -t ${{ github.event.repository.name }} .
            echo "EUREKA_URL=http://discovery-service:8761/eureka" >> .env
            docker rm -f ${{ github.event.repository.name }}
            docker run --name ${{ github.event.repository.name }} --network all_connected -d -p 8080:8080 --env-file .env ${{ github.event.repository.name }}
            echo "Docker container running..."
            rm .env
